version: "3.9"

services:
  postgres:
    image: postgres:alpine3.18
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yomi
      POSTGRES_PASSWORD: yomi123
      POSTGRES_DB: main
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
